import {
  insertDocument,
  connectDatabase,
  getAllDocuments,
} from "../../../helpers/db-utils";

async function handler(req, res) {
  // eventId of events card
  const eventId = req.query.eventId;

  let client;

  try {
    client = await connectDatabase();
  } catch (error) {
    res.status(500).json({ message: "Connecting to database failed!" });
    return;
  }

  if (req.method === "POST") {
    // add server side validation
    const { email, name, text } = req.body;
    if (
      !email.includes("@") ||
      !name ||
      name.trim() === "" ||
      !text ||
      text.trim() === ""
    ) {
      res.status(422).json({ message: "Invalid Input" });
      client.close();
      return;
    }

    // storing eventId for any future reference which help in scalling
    const newComment = {
      email,
      name,
      text,
      eventId,
    };

    let result;
    try {
      result = await insertDocument(client, "comments", newComment);

      // Setting the default id generated by mongodb for the comment inside the comment
      newComment._id = result.insertedId;

      res.status(201).json({ message: "Added Comment", comment: newComment });
    } catch (error) {
      res.status(500).json({ message: "Inserting Comment failed!" });
    }
  }
  if (req.method === "GET") {
    try {
      // getAllDocuments declared in db-utls.js file
      const documents = await getAllDocuments(client, "comments", { _id: -1 });

      res.status(200).json({ comments: documents });
    } catch (error) {
      res.status(500).json({ message: "Getting comments failed!" });
    }
  }
  client.close();
}
export default handler;
